[project]
name = "anki-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anki-export>=0.1.4",
    "ankisync2>=0.3.4",
    "genanki>=0.13.1",
]
